### ISSUE TITLE
Allow users to search existing sets

### ISSUE THREAD

**Issue by fgafford** [avast-ye-matey/bricklist#1]
(I know this is redundant and is already working in the deployed version but I want to help you from the ground up to do this the correct way and allow for smaller reviews and fixes as we go)

Make it so that a user is able to search set from the existing data source (we will use a different data source in the future. 

**Requirements:**
- [x]  User is able to enter free text and search for sets
- [x] The search will run every time there is change to the search text (automatically, per every letter)

**Resources/Tips**: 
- [x] Use the useState (React.useState()) for storing the state of the search input.
- [x] Don't use any document.getElement... stuff, do thing the react way instead.

**Comment by avast-ye-matey** [comment]
Added input filed. Each letter triggers an onChange event and re-searched list. Utilized useState hook for storing input value. Did not use document.getElement.

**Comment by fgafford** [comment]
Working. Looks good!
